import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/elements/nav-bar";
import { Button } from "@/components/ui/button";
import Header from "@/components/elements/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Mock design to flow */}
        {/* <img src="/images/design.jpg" className="fixed top-0 left-0 z-[1]"></img> */}

        <div className="relative z-10 flex px-0 lg:px-10">
          <NavBar />
          <div className="flex flex-col gap-4 lg:gap-6 w-full px-4 lg:px-6 py-4 lg:py-12">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
